export UPSTREAM_GERRIT_HOST_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCkX4scr5yYBSua5S6bNQRsGVgT3jT5bgPp6KbxN2kHuhidro3jz54+1MzQd2BPh53zcOXFaFQl1qtjLmOl620ccNPi/6zlofN7f8pPBQhMNZsQIjnLJiJPZ7OUtGlQcfxbSUCZJoruwmBcIh5LHt1ma5GyQXBO9ZAjaiQsjleJdQ=="
export GIT_EMAIL='zhou.lichao@zte.com.cn'
export GIT_NAME='zhoulichao'
export UPSTREAM_GERRIT_USER=zteopenstackCI
export UPSTREAM_GERRIT_SSH_KEY_PATH=gerrit_key
export JENKINS_SSH_KEY_PATH=jenkins_key
export PUBLISH_HOST=127.0.0.1
